class DomainError(Exception): ...
class StreamerAlreadyExistsError(DomainError): ...
class StreamerNotFoundError(DomainError): ...
class StreamerLimitReachedError(DomainError): ...
class StreamerNotOnTwitchError(DomainError): ...
class ChannelNotConfiguredError(DomainError): ...