from abc import ABC, abstractmethod

class ILogger(ABC):
    @abstractmethod
    def info(self, event: str, **kwargs) -> None: ...
    @abstractmethod
    def warning(self, event: str, **kwargs) -> None: ...
    @abstractmethod
    def error(self, event: str, **kwargs) -> None: ...
    @abstractmethod
    def debug(self, event: str, **kwargs) -> None: ...